
<div class="progressbar-header">
    <span class="progressbar-header-title">Place your order by 3:00pm for Same Day Shipping!</span>
</div>
<div style="width: 300px;" class="progressbar-container">

    <div id="progressbar" class="uk-progress uk-progress-success">
        <div class="uk-progress-bar" style="width: 0%;">0%</div>
    </div>
</div>
<div class="progressbar-display">
    <div id="progressbar-nextday">Next Day</div>
    <div id="progressbar-sameday">Same Day</div>
</div>
<script>
requirejs( [ 'require', 'jquery',  'UIkit' ],
function( require, $, UIkit ) {

    $(document).ready(function () {             
        var bar = document.getElementById('progressbar');  
        var barmessage = $('.uk-progress-bar');

        bar.max  = 50;
        bar.value  = 1;                               
        var percent = Math.floor(( bar.value  /  bar.max) * 100);
        var progressText = '';
        switch (Math.floor(percent / 20)) {
            case '2':
                progressText = 'Don\'t waste time.';
                break;
            case '3':
                progressText = 'Time flies by!!';
                break;
            case '4':
                progressText = 'Hurry Up for free shipping!!';
                break;
        }
        barmessage.css('width', percent + '%').text(progressText);        
        
        var animate = setInterval(function () {
                bar.value += 1;
                var percent = Math.floor(( bar.value  /  bar.max) * 100);
                barmessage.css('width', percent + '%').text(bar.value + ' out of ' + bar.max + ' Completed.');
                if (bar.value >= bar.max) {
                clearInterval(animate);
                }

        }, 1000);
    });
});
</script>
<script>
/*
requirejs( [ 'require', 'jquery',  'uikit' ],
function( require, $, uikit ) {
            
   $(window).load(function () {             
        var bar = document.getElementById('progressbar');                                
        bar.max  = 50; // Total Steps
        bar.value  = 1; // completed Steps                
        var barmessage = $('.uk-progress-bar');                
        var percent = Math.floor(( bar.value  /  bar.max) * 100);
        barmessage.css('width', percent + '%').text(bar.value + ' out of '+bar.max+' Completed.');        
        
        var animate = setInterval(function () {
                bar.value += 1;
                var percent = Math.floor(( bar.value  /  bar.max) * 100);
                barmessage.css('width', percent + '%').text(bar.value + ' out of '+bar.max+' Completed.');
                if (bar.value >= bar.max) {
                clearInterval(animate);
                }

        }, 1000);
    });                 
});*/
</script>
